# NumPy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.1'

### array()

In [3]:
my_list = [-10, -4, 0, 7, 9]
my_array = np.array(my_list)
print(my_list)
print(my_array)

[-10, -4, 0, 7, 9]
[-10  -4   0   7   9]


Multiply every element by 10:

In [4]:
[10*x for x in my_array]

[-100, -40, 0, 70, 90]

In [5]:
my_array * 10

array([-100,  -40,    0,   70,   90])

### arange()

In [6]:
my_list * 3

[-10, -4, 0, 7, 9, -10, -4, 0, 7, 9, -10, -4, 0, 7, 9]

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_range_array = np.arange(10,25) - 10 +1
my_range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
my_range_array.size

15

In [10]:
np.arange(10,25,5) #start, stop, step values

array([10, 15, 20])

In [11]:
np.arange(15, step=5)

array([ 0,  5, 10])

### linspace()

In [12]:
np.linspace(5, 15, 4) # start, stop, spacenum valueas spacenum=50 by default

array([ 5.        ,  8.33333333, 11.66666667, 15.        ])

In [13]:
my_linspace = np.linspace(5, 15, 3, retstep=True)
my_linspace

(array([ 5., 10., 15.]), 5.0)

In [14]:
type(my_linspace)

tuple

In [15]:
my_linspace[1]

5.0

In [16]:
my_linspace[0]

array([ 5., 10., 15.])

### zeros() and ones()

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
my_zeros = np.zeros((2,3))
print(type(my_zeros))
print(len(my_zeros))
my_zeros

<class 'numpy.ndarray'>
2


array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [21]:
np.zeros(7, dtype='bool')

array([False, False, False, False, False, False, False])

### Two Dimentional Arrays, shape

In [22]:
my_matrix = np.arange(35)
my_matrix.shape

(35,)

In [23]:
my_matrix.shape = (5,7)
my_matrix

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [24]:
my_matrix.shape 

(5, 7)

In [25]:
my_matrix.size

35

In [26]:
my_matrix[2]

array([14, 15, 16, 17, 18, 19, 20])

In [27]:
my_matrix[3,1]

22

In [28]:
my_matrix[3][1]

22

### Three Dimentional Arrays

In [29]:
my_3D_array = np.arange(60)
my_3D_array.shape = (3,4,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [30]:
my_3D_array[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
my_3D_array[1,2]

array([30, 31, 32, 33, 34])

In [32]:
my_3D_array[2,0,4]

44

In [33]:
my_3D_array[2][0][4]

44

### Boolean Mask Arrays

In [34]:
my_vector = np.arange(1,10)
print(my_vector)
zero_mod3_mask = 0 == (my_vector % 3)
zero_mod3_mask

[1 2 3 4 5 6 7 8 9]


array([False, False,  True, False, False,  True, False, False,  True])

In [35]:
sub_array = my_vector[zero_mod3_mask]
sub_array

array([3, 6, 9])

In [36]:
sub_array[sub_array>5]

array([6, 9])

### Logical Operatiors

In [37]:
my_vector = np.arange(-9,10)
mod_test = 0 == (my_vector % 7)
print(my_vector, my_vector.size)
mod_test

[-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9] 19


array([False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False])

In [38]:
positive_test = my_vector > 0
positive_test

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [39]:
combined_mask = np.logical_and(mod_test, positive_test)
combined_mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False])

In [40]:
my_vector[combined_mask]

array([7])

### Broadcasting

In [41]:
print(my_3D_array.ndim, my_3D_array.size, my_3D_array.shape, my_3D_array.dtype, sep='\n')
my_3D_array

3
60
(3, 4, 5)
int32


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [42]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))
print(left_mat, right_mat, sep='\n\n')

[[0 1 2]
 [3 4 5]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [43]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [44]:
right_mat.shape = (5,3)
right_mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [45]:
np.inner(left_mat, right_mat)

array([[  5,  14,  23,  32,  41],
       [ 14,  50,  86, 122, 158]])

### Operations along axes

In [46]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [47]:
my_3D_array.sum()

1770

\begin{equation*}
\sum_{k=1}^n a_k =
\frac{n*(n+1)}2
\end{equation*}

In [48]:
59 * 60 / 2

1770.0

In [49]:
my_3D_array.sum(axis=0)

array([[ 60,  63,  66,  69,  72],
       [ 75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102],
       [105, 108, 111, 114, 117]])

In [50]:
my_3D_array.sum(axis=1)

array([[ 30,  34,  38,  42,  46],
       [110, 114, 118, 122, 126],
       [190, 194, 198, 202, 206]])

In [51]:
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85],
       [110, 135, 160, 185],
       [210, 235, 260, 285]])

### Broadcasting Rules

In [52]:
my_2D_array = np.ones(20, dtype='int').reshape((4,5))*3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [53]:
my_random_2D_array = np.random.random((4,5))
my_random_2D_array

array([[0.35344943, 0.0928722 , 0.99808023, 0.23268065, 0.40498062],
       [0.0195941 , 0.10240741, 0.14075041, 0.63578696, 0.77028005],
       [0.19717644, 0.711166  , 0.52465951, 0.63162146, 0.65894548],
       [0.70830213, 0.65648802, 0.37212165, 0.69872283, 0.78043671]])

In [54]:
my_3D_array * my_2D_array

array([[[  0,   3,   6,   9,  12],
        [ 15,  18,  21,  24,  27],
        [ 30,  33,  36,  39,  42],
        [ 45,  48,  51,  54,  57]],

       [[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]],

       [[120, 123, 126, 129, 132],
        [135, 138, 141, 144, 147],
        [150, 153, 156, 159, 162],
        [165, 168, 171, 174, 177]]])

In [55]:
my_3D_array * 3

array([[[  0,   3,   6,   9,  12],
        [ 15,  18,  21,  24,  27],
        [ 30,  33,  36,  39,  42],
        [ 45,  48,  51,  54,  57]],

       [[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]],

       [[120, 123, 126, 129, 132],
        [135, 138, 141, 144, 147],
        [150, 153, 156, 159, 162],
        [165, 168, 171, 174, 177]]])

In [56]:
np.set_printoptions(precision=4)
my_3D_array * my_random_2D_array

array([[[ 0.    ,  0.0929,  1.9962,  0.698 ,  1.6199],
        [ 0.098 ,  0.6144,  0.9853,  5.0863,  6.9325],
        [ 1.9718,  7.8228,  6.2959,  8.2111,  9.2252],
        [10.6245, 10.5038,  6.3261, 12.577 , 14.8283]],

       [[ 7.069 ,  1.9503, 21.9578,  5.3517,  9.7195],
        [ 0.4899,  2.6626,  3.8003, 17.802 , 22.3381],
        [ 5.9153, 22.0461, 16.7891, 20.8435, 22.4041],
        [24.7906, 23.6336, 13.7685, 26.5515, 30.437 ]],

       [[14.138 ,  3.8078, 41.9194, 10.0053, 17.8191],
        [ 0.8817,  4.7107,  6.6153, 30.5178, 37.7437],
        [ 9.8588, 36.2695, 27.2823, 33.4759, 35.5831],
        [38.9566, 36.7633, 21.2109, 40.5259, 46.0458]]])

In [57]:
my_vector = np.arange(1,6) * 7
my_vector

array([ 7, 14, 21, 28, 35])

In [58]:
my_3D_array / my_vector

array([[[0.    , 0.0714, 0.0952, 0.1071, 0.1143],
        [0.7143, 0.4286, 0.3333, 0.2857, 0.2571],
        [1.4286, 0.7857, 0.5714, 0.4643, 0.4   ],
        [2.1429, 1.1429, 0.8095, 0.6429, 0.5429]],

       [[2.8571, 1.5   , 1.0476, 0.8214, 0.6857],
        [3.5714, 1.8571, 1.2857, 1.    , 0.8286],
        [4.2857, 2.2143, 1.5238, 1.1786, 0.9714],
        [5.    , 2.5714, 1.7619, 1.3571, 1.1143]],

       [[5.7143, 2.9286, 2.    , 1.5357, 1.2571],
        [6.4286, 3.2857, 2.2381, 1.7143, 1.4   ],
        [7.1429, 3.6429, 2.4762, 1.8929, 1.5429],
        [7.8571, 4.    , 2.7143, 2.0714, 1.6857]]])

In [59]:
my_3D_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [ 3, 11, 12, 13, 14],
        [ 1,  2, 17, 18, 19]],

       [[ 6,  7,  1, 23, 24],
        [ 4, 12,  6,  0, 29],
        [ 2,  3, 11,  5, 34],
        [ 0,  8, 16, 10,  4]],

       [[ 5, 13,  0, 15,  9],
        [ 3,  4,  5, 20, 14],
        [ 1,  9, 10, 25, 19],
        [ 6,  0, 15,  2, 24]]], dtype=int32)

### Structured and Record Arrays

In [60]:
person_data_def = [('name','S6'),('height','f8'),('weight','f8'),('age','i8')] #S:String, f:floating point, i:integer
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [61]:
people_array = np.zeros((4,), dtype=person_data_def)
people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [62]:
people_array[3] = ('Bob', 80, 200, 20)
people_array

array([(b'',  0.,   0.,  0), (b'',  0.,   0.,  0), (b'',  0.,   0.,  0),
       (b'Bob', 80., 200., 20)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [63]:
ages = people_array['age']
ages

array([ 0,  0,  0, 20], dtype=int64)

In [64]:
people_big_array = np.zeros((4,3,2), dtype=person_data_def)
people_big_array

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [65]:
people_big_array[3,2,1] = ('Alice',160,140,30)
people_big_array

array([[[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)]],

       [[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)]],

       [[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)]],

       [[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'Alice', 160., 140., 30)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [66]:
person_record_array = np.rec.array([('Alice',160,140,30),('Bob', 80, 200, 20)], dtype=person_data_def)
person_record_array

rec.array([(b'Alice', 160., 140., 30), (b'Bob',  80., 200., 20)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [67]:
person_record_array[0].age

30

In [68]:
person_record_array['age']

array([30, 20], dtype=int64)

## Plots

In [69]:
%matplotlib inline

In [70]:
import matplotlib.pyplot as pl
