# NumPy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.1'

### array()

In [19]:
my_list = [-10, -4, 0, 7, 9]
my_array = np.array(my_list)
print(my_list)
print(my_array)

[-10, -4, 0, 7, 9]
[-10  -4   0   7   9]


Multiply every element by 10:

In [20]:
[10*x for x in my_array]

[-100, -40, 0, 70, 90]

In [22]:
my_array * 10

array([-100,  -40,    0,   70,   90])

### arange()

In [25]:
my_list * 3

[-10, -4, 0, 7, 9, -10, -4, 0, 7, 9, -10, -4, 0, 7, 9]

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
my_range_array = np.arange(10,25) - 10 +1
my_range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
my_range_array.size

15

In [47]:
np.arange(10,25,5) #start, stop, step values

array([10, 15, 20])

In [48]:
np.arange(15, step=5)

array([ 0,  5, 10])

### linspace()

In [51]:
np.linspace(5, 15, 4) # start, stop, spacenum valueas spacenum=50 by default

array([ 5.        ,  8.33333333, 11.66666667, 15.        ])

In [72]:
my_linspace = np.linspace(5, 15, 3, retstep=True)
my_linspace

(array([ 5., 10., 15.]), 5.0)

In [74]:
type(my_linspace)

tuple

In [75]:
my_linspace[1]

5.0

In [76]:
my_linspace[0]

array([ 5., 10., 15.])

### zeros() and ones()

In [77]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [90]:
my_zeros = np.zeros((2,3))
print(type(my_zeros))
print(len(my_zeros))
my_zeros

<class 'numpy.ndarray'>
2


array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [102]:
np.zeros(7, dtype='bool')

array([False, False, False, False, False, False, False])

### Two Dimentional Arrays, shape

In [108]:
my_matrix = np.arange(35)
my_matrix.shape

(35,)

In [110]:
my_matrix.shape = (5,7)
my_matrix

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [113]:
my_matrix.shape 

(5, 7)

In [114]:
my_matrix.size

35

In [115]:
my_matrix[2]

array([14, 15, 16, 17, 18, 19, 20])

In [116]:
my_matrix[3,1]

22

In [117]:
my_matrix[3][1]

22

### Three Dimentional Arrays

In [2]:
my_3D_array = np.arange(60)
my_3D_array.shape = (3,4,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [3]:
my_3D_array[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
my_3D_array[1,2]

array([30, 31, 32, 33, 34])

In [5]:
my_3D_array[2,0,4]

44

In [6]:
my_3D_array[2][0][4]

44

### Boolean Mask Arrays

In [7]:
my_vector = np.arange(1,10)
print(my_vector)
zero_mod3_mask = 0 == (my_vector % 3)
zero_mod3_mask

[1 2 3 4 5 6 7 8 9]


array([False, False,  True, False, False,  True, False, False,  True])

In [8]:
sub_array = my_vector[zero_mod3_mask]
sub_array

array([3, 6, 9])

In [9]:
sub_array[sub_array>5]

array([6, 9])

### Logical Operatiors

In [10]:
my_vector = np.arange(-9,10)
mod_test = 0 == (my_vector % 7)
print(my_vector, my_vector.size)
mod_test

[-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9] 19


array([False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False])

In [11]:
positive_test = my_vector > 0
positive_test

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [12]:
combined_mask = np.logical_and(mod_test, positive_test)
combined_mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False])

In [13]:
my_vector[combined_mask]

array([7])

### Broadcasting

In [14]:
print(my_3D_array.ndim, my_3D_array.size, my_3D_array.shape, my_3D_array.dtype, sep='\n')
my_3D_array

3
60
(3, 4, 5)
int32


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [15]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))
print(left_mat, right_mat, sep='\n\n')

[[0 1 2]
 [3 4 5]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [17]:
right_mat.shape = (5,3)
right_mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
np.inner(left_mat, right_mat)

array([[  5,  14,  23,  32,  41],
       [ 14,  50,  86, 122, 158]])

### Operations along axes

In [19]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [20]:
my_3D_array.sum()

1770

\begin{equation*}
\sum_{k=1}^n a_k =
\frac{n*(n+1)}2
\end{equation*}

In [21]:
59 * 60 / 2

1770.0

In [22]:
my_3D_array.sum(axis=0)

array([[ 60,  63,  66,  69,  72],
       [ 75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102],
       [105, 108, 111, 114, 117]])

In [23]:
my_3D_array.sum(axis=1)

array([[ 30,  34,  38,  42,  46],
       [110, 114, 118, 122, 126],
       [190, 194, 198, 202, 206]])

In [24]:
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85],
       [110, 135, 160, 185],
       [210, 235, 260, 285]])

### Broadcasting Rules

In [25]:
my_2D_array = np.ones(20, dtype='int').reshape((4,5))*3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [26]:
my_random_2D_array = np.random.random((4,5))
my_random_2D_array

array([[0.69103002, 0.29714667, 0.57014454, 0.34851118, 0.36114468],
       [0.25039161, 0.64369269, 0.47040518, 0.33057825, 0.25101492],
       [0.75840873, 0.76907618, 0.02834863, 0.09965377, 0.8133405 ],
       [0.04893268, 0.56160688, 0.47491463, 0.74042931, 0.12589637]])

In [30]:
my_3D_array * my_2D_array

array([[[  0,   3,   6,   9,  12],
        [ 15,  18,  21,  24,  27],
        [ 30,  33,  36,  39,  42],
        [ 45,  48,  51,  54,  57]],

       [[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]],

       [[120, 123, 126, 129, 132],
        [135, 138, 141, 144, 147],
        [150, 153, 156, 159, 162],
        [165, 168, 171, 174, 177]]])

In [28]:
my_3D_array * 3

array([[[  0,   3,   6,   9,  12],
        [ 15,  18,  21,  24,  27],
        [ 30,  33,  36,  39,  42],
        [ 45,  48,  51,  54,  57]],

       [[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]],

       [[120, 123, 126, 129, 132],
        [135, 138, 141, 144, 147],
        [150, 153, 156, 159, 162],
        [165, 168, 171, 174, 177]]])

In [31]:
np.set_printoptions(precision=4)
my_3D_array * my_random_2D_array

array([[[ 0.    ,  0.2971,  1.1403,  1.0455,  1.4446],
        [ 1.252 ,  3.8622,  3.2928,  2.6446,  2.2591],
        [ 7.5841,  8.4598,  0.3402,  1.2955, 11.3868],
        [ 0.734 ,  8.9857,  8.0735, 13.3277,  2.392 ]],

       [[13.8206,  6.2401, 12.5432,  8.0158,  8.6675],
        [ 6.2598, 16.736 , 12.7009,  9.2562,  7.2794],
        [22.7523, 23.8414,  0.9072,  3.2886, 27.6536],
        [ 1.7126, 20.2178, 17.5718, 28.1363,  4.91  ]],

       [[27.6412, 12.183 , 23.9461, 14.986 , 15.8904],
        [11.2676, 29.6099, 22.109 , 15.8678, 12.2997],
        [37.9204, 39.2229,  1.4741,  5.2817, 43.9204],
        [ 2.6913, 31.45  , 27.0701, 42.9449,  7.4279]]])

In [32]:
my_vector = np.arange(1,6) * 7
my_vector

array([ 7, 14, 21, 28, 35])

In [33]:
my_3D_array / my_vector

array([[[0.    , 0.0714, 0.0952, 0.1071, 0.1143],
        [0.7143, 0.4286, 0.3333, 0.2857, 0.2571],
        [1.4286, 0.7857, 0.5714, 0.4643, 0.4   ],
        [2.1429, 1.1429, 0.8095, 0.6429, 0.5429]],

       [[2.8571, 1.5   , 1.0476, 0.8214, 0.6857],
        [3.5714, 1.8571, 1.2857, 1.    , 0.8286],
        [4.2857, 2.2143, 1.5238, 1.1786, 0.9714],
        [5.    , 2.5714, 1.7619, 1.3571, 1.1143]],

       [[5.7143, 2.9286, 2.    , 1.5357, 1.2571],
        [6.4286, 3.2857, 2.2381, 1.7143, 1.4   ],
        [7.1429, 3.6429, 2.4762, 1.8929, 1.5429],
        [7.8571, 4.    , 2.7143, 2.0714, 1.6857]]])

In [34]:
my_3D_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [ 3, 11, 12, 13, 14],
        [ 1,  2, 17, 18, 19]],

       [[ 6,  7,  1, 23, 24],
        [ 4, 12,  6,  0, 29],
        [ 2,  3, 11,  5, 34],
        [ 0,  8, 16, 10,  4]],

       [[ 5, 13,  0, 15,  9],
        [ 3,  4,  5, 20, 14],
        [ 1,  9, 10, 25, 19],
        [ 6,  0, 15,  2, 24]]], dtype=int32)

### Structured and Record Arrays

In [67]:
person_data_def = [('name','S6'),('height','f8'),('weight','f8'),('age','i8')] #S:String, f:floating point, i:integer
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [68]:
people_array = np.zeros((4,), dtype=person_data_def)
people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [69]:
people_array[3] = ('Bob', 80, 200, 20)
people_array

array([(b'',  0.,   0.,  0), (b'',  0.,   0.,  0), (b'',  0.,   0.,  0),
       (b'Bob', 80., 200., 20)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [73]:
ages = people_array['age']
ages

array([ 0,  0,  0, 20], dtype=int64)

In [74]:
people_big_array = np.zeros((4,3,2), dtype=person_data_def)
people_big_array

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [76]:
people_big_array[3,2,1] = ('Alice',160,140,30)
people_big_array

array([[[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)]],

       [[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)]],

       [[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)]],

       [[(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'',   0.,   0.,  0)],
        [(b'',   0.,   0.,  0), (b'Alice', 160., 140., 30)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [77]:
person_record_array = np.rec.array([('Alice',160,140,30),('Bob', 80, 200, 20)], dtype=person_data_def)
person_record_array

rec.array([(b'Alice', 160., 140., 30), (b'Bob',  80., 200., 20)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [81]:
person_record_array[0].age

30

In [82]:
person_record_array['age']

array([30, 20], dtype=int64)

## Plots

In [83]:
%matplotlib inline

In [ ]:
import matplotlib.pyplot as pl
